export default [
  'Web Developers',
  'Graphic Design',
  'Marketing Specialist',
  'UI/UX Designer',
  'Mobile Developers',
  'Copywriters',
  'Admin Support',
  'Customer Service',
  'Marketing Research Analysts',
  'Project Managers',
  'Product Designers',
  'Data Entry',
  'SEO Experts',
  'Backend Developers',
  ' Data Analysis',
  'Full stack developers',
  ' Accounting',
];
